pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                timeout(time: 3, units: 'MINUTES') {
                    retry (5) {
                        sh './flakey-deploy.sh'
                    }
                }
            }
        }
    }
}